[숫자 야구 게임] 윤정욱 미션 제출합니다.
woowacourse-precourse/java-baseball pull request #13
Opened 2022-11-07 05:05 UTC by wugawuga

2022-11-09 14:21 UTC, seondays reviewed
안녕하세요, 먼저 리뷰 남겨주셔서 감사합니다. 저도 부족하지만 코멘트를 달아 드렸어요. 3주차도 화이팅 하시길 바랍니다!

2022-11-09 14:21 UTC, seondays commented on src/main/java/baseball/BaseballGame.java
> +    }
while 반복문 돌리실 때에 사용하신 true를 변수로 선언하셔서 사용하시면, 더 조건을 명확하게 알 수 있지 않을까 하고 의견 드립니다!

2022-11-09 14:21 UTC, seondays commented on src/main/java/baseball/BaseballGame.java
> +    }
숫자 range의 범위도 함께 상수로 처리하는 것을 고려해보셔도 좋을 것 같아요!

2022-11-09 15:57 UTC, wugawuga commented on src/main/java/baseball/BaseballGame.java
> +    }
flag 를 처음에 썼다가 필요 없을 것 지웠는데 다시 생각해보니 필요할 것 같아요!!

2022-11-10 01:19 UTC, slbin-park requested changes

2022-11-10 07:55 UTC, wugawuga commented on src/test/java/baseball/BaseballGameTest.java
> +}
감사합니다!! 함수명 짓는게 진짜 어려운 것 같아요ㅠㅠ

2022-11-10 07:56 UTC, wugawuga commented on src/main/java/baseball/BaseballGame.java
> +        return ballOrStrike(strike, ball);
이 부분을 고민 했었는데 딱 집어주셨네요!! 감사합니다

2022-11-10 07:57 UTC, wugawuga commented on src/main/java/baseball/BaseballGame.java
> +        if (computer.contains(user.get(i)) && Objects.equals(computer.get(i), user.get(i))) {
생각도 못했네요ㅜㅜ 앞 부분 생략 가능하다니,,,,

2023-08-30 15:35 UTC, closed without merging